name: Deploy SAM Application

on:
  push:
    branches:
      - release
  pull_request:
    branches:
      - release

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install SAM CLI
        run: |
          pip install aws-sam-cli
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
          
      - name: SAM Package
        run: aws cloudformation package --s3-bucket lunchplannerv2-lambdas --template-file template.yaml --output-template-file gen/template-generated.yaml
          
      - name: SAM deploy
        run: aws cloudformation deploy --template-file gen/template-generated.yaml --stack-name lunchplannerv2 --capabilities CAPABILITY_IAM --region eu-central-1 --no-fail-on-empty-changeset

      - name: Install dependencies
        run: |
          cd src/client
          npm ci
      
      - name: Build app
        run: |
          cd src/client
          npm run build

      - name: Deploy to S3
        run: |
          aws s3 sync src/client/build/ s3://lunchplanner-v2-client/ --delete
      
      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation --distribution-id E37IKOJFJFNNIL --paths "/*"
